### ISSUE TITLE
how to remove event click?

### ISSUE THREAD

**Issue by fahmihwan** [torrobinson/progress-steps-webcomponent#2]
how to remove event click? but not disabled.

**Comment by torrobinson** [comment]
Hey @fahmihwan there is no option for this implemented yet, but you could always add some CSS somewhere globally like
```css
progress-steps{
  pointer-events: none;
}
```

To prevent click events from registering anywhere in the control, making it "ready only", if you will.
